global:
  scrape_interval: 15s

scrape_configs:
- job_name: grandapp
  static_configs:
  - targets: ['10.0.0.6:9100']
  
- job_name: grandpipe
  static_configs:
  - targets: ['10.0.0.5:9100']

- job_name: cadvisor
  static_configs:
  - targets: ['10.0.0.5:8080']