localTimeZone: US/Pacific #US/Pacific, US/Mountain, US/Central, US/Eastern
restUrl: http://localhost:5000/api/status/
points: 60
brokerUrl: ["localhost:9093"]
topic: test
assetName: SmartSensor01
sensorId: SmartSensor01
sensorType: Vibration
