localTimeZone: US/Pacific #US/Pacific, US/Mountain, US/Central, US/Eastern
restUrl: http://localhost:5000/api/status/
points: 60
brokerUrl: ["localhost:9092"]
topic: test
assetName: Sensor01
sensorId: Sensor01
sensorType: Vibration
