localTimeZone: US/Pacific #US/Pacific, US/Mountain, US/Central, US/Eastern
restUrl: http://68.10.56.28:5000/api/status/
points: 60
brokerUrl: ["poc01.westus.cloudapp.azure.com:9092"]
topic: test
assetName: SmartSensor01
sensorId: SmartSensor01
sensorType: Vibration
