version: "3.8"

networks:
  private:
    external: true
    name: apm-net

services:
  zk-exporter:
    image: dabealu/zookeeper-exporter
    ports:
      - 9141:8080
    command: --zk-hosts="zoo1:2181,zoo2:2181,zoo3:2181"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      private:

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.2.0
    command: --kafka.server=tasks.kafka01:9092 --kafka.server=tasks.kafka02:9092 --kafka.server=tasks.kafka03:9092
    ports:
     # Following the scheme, https://github.com/prometheus/prometheus/wiki/Default-port-allocations
     - 9308:9308
    deploy:
      mode: replicated
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M      
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      endpoint_mode: vip
    networks:
      private:
