version: "3.8"

volumes:
  zk-data:
  zk-txn-logs:

networks:
  private:
    external: true
    name: apm-net

services:
  zoo1:
    image: zookeeper:3.4.14
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zk-data:/data
      - zk-txn-logs:/datalog
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname==grandview-test-07
    networks:
      private:

  zoo2:
    image: zookeeper:3.4.14
    hostname: zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zk-data:/data
      - zk-txn-logs:/datalog
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname==grandview-test-08
    networks:
      private:

  zoo3:
    image: zookeeper:3.4.14
    hostname: zoo3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zk-data:/data
      - zk-txn-logs:/datalog
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname==grandview-test-09
    networks:
      private: