brokerUrl: ["poc01.westus.cloudapp.azure.com:9092"]
assetList: ["Robot01"]
topic: apm-trace-default-nest-01
filePath: ./sensor.csv
sensorType: "Laser"
sensorId: "L01"
interval: "30s"
loop: 10000
startIdx: 3
lot: 11
substrate: 12
substType: 13
substLocation: 14
processJob: 15
controlJob: 16
recipeName: 17