version: '3.1'
  
volumes:
  zk_data:
  kafka_data:

networks:
  stream:

services:
  zoo1:
    image: zookeeper:3.4
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '100m'
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      - stream

  zoo2:
    image: zookeeper:3.4
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '100m'
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      - stream

  zoo3:
    image: zookeeper:3.4
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '100m'
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    networks:
      - stream

  kafka1:
    image: confluentinc/cp-kafka:4.1.3
    hostname: kafka1
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '500m'
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - stream

  kafka2:
    image: confluentinc/cp-kafka:4.1.3
    hostname: kafka2
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '500m'
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - stream

  kafka3:
    image: confluentinc/cp-kafka:4.1.3
    hostname: kafka3
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '500m'
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - stream

  jobmanager:
    image: flink:1.9.1-scala_2.11
    ports:
      - 8081:8081
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - stream

  taskmanager:
    image: flink:1.9.1-scala_2.11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 3
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    networks:
      - stream

  db:
    image: mariadb:10.4.12
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: bistel01
      